---
# Kyverno policy: Blocking privileged containers.
# CIS Docker Benchmark 5.04 - Ensure that privileged containers are not used

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privileged-containers
  annotations:
    policies.kyverno.io/title: Block privileged containers
    policies.kyverno.io/category: Pod Security / Docker Hardening
    policies.kyverno.io/severity: critical
    policies.kyverno.io/subject: Pod, Container
    policies.kyverno.io/description: >-
      Privileged container has full access to host and isolation is not possible.
      Equal to launching process directly on host with root privileges. ALWAYS forbidden.
    audit-controls: "CIS-5.4, NIST-AC-6, PCI-DSS-7.2"
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: disallow-privileged
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: >-
          CRITICAL: Privileged containers are FORBIDDEN!
          securityContext.privileged MUST NOT be set true.
          Privileged containers has full access to host system.
        pattern:
          spec:
            =(initContainers):
              - =(securityContext):
                  =(privileged): false
            containers:
              - =(securityContext):
                  =(privileged): false

    - name: disallow-host-pid
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: >-
          Container MUST NOT use host's PID namespace (hostPID: true).
          It grants full access to all host processes.
        pattern:
          spec:
            =(hostPID): false

    - name: disallow-host-network
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: >-
          Container MUST NOT use host's network (hostNetwork: true).
          It grants full access to all host network interfaces.
        pattern:
          spec:
            =(hostNetwork): false

    - name: disallow-host-ipc
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: >-
          Container MUST NOT use IPC host space (hostIPC: true).
          It grants full access to host shared memory.
        pattern:
          spec:
            =(hostIPC): false

    - name: disallow-allow-privilege-escalation
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: >-
          allowPrivilegeEscalation MUST be set false.
          It prevents privilege escalation by subprocess.
        pattern:
          spec:
            containers:
              - securityContext:
                  allowPrivilegeEscalation: false
