apiVersion: v1
kind: Pod
metadata:
  name: insecure-app
  namespace: default
  labels:
    app: insecure-app
spec:
  containers:
    - name: app-container
      image: ubuntu:latest 
      command: ["sleep", "3600"]            
      
      securityContext:
        privileged: true
        runAsUser: 0   
        runAsGroup: 0
        readOnlyRootfs: false 
        allowPrivilegeEscalation: true
        
      volumeMounts:
        - name: host-root
          mountPath: /host
          
  volumes:
    - name: host-root
      hostPath:
        path: /